

trigger:
- none

pool: default

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Installing Node.js'

- script: "npx codeceptjs run --steps"
  displayName: 'Running Tests'
  
    

