

trigger:
- none

pool: default

steps:

- script: "npm i"
  displayName: 'Installing dependencies'


- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Installing Node.js'

- script: "npx codeceptjs run --reporter mocha-multi"
  displayName: 'Running Tests'
  
- task: PublishHtmlReport@1
  inputs:
     reportDir: 'output/report.html'
  displayName: 'Publish HTML Report'
  
    

