

trigger:
- none

pool: default

steps:
- script: |
    displayName: 'CodeceptJS Demo Project'
    echo CodeceptJS Demo Project
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Installing Node.js'

- script: |
    displayName: 'Running Tests'
    npx codeceptjs run --steps
    

